image: python:3.7

pipelines:
  branches:
    master:
      - parallel:
          - step:
              name: Master test - suite1
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "desktop" -v pages/ --junitxml=test-reports/report.xml
          - step:
              name: Master test - suite2
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "laptop" -v pages/ --junitxml=test-reports/report.xml

  custom:
    prod-pipeline:
      - parallel:
          - step:
              name: Prod test - suite1
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "desktop" -v pages/ --junitxml=test-reports/report.xml
          - step:
              name: Prod test - suite2
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "laptop" -v pages/ --junitxml=test-reports/report.xml

    staging1-pipeline:
       - parallel:
          - step:
              name: Staging1 test - suite1
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "desktop" -v pages/ --url stag1 --junitxml=test-reports/report.xml
          - step:
              name: Staging1 test - suite2
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "laptop" -v pages/ --url stag1 --junitxml=test-reports/report.xml

    staging2-pipeline:
      - parallel:
          - step:
              name: Staging2 test - suite1
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "desktop" -v pages/ --url stag2 --junitxml=test-reports/report.xml
          - step:
              name: Staging2 test - suite2
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - python -m pytest -m "laptop" -v pages/ --url stag2 --junitxml=test-reports/report.xml