image: python:3.9

pipelines:
  branches:
    master:
      - step:
          name: Test
          caches:
            - pip
          script:
            - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pytest -v homepage/test_homepage.py::test_bad_email

  pull-requests:
     '**':
      - step:
          name: Test
          caches:
            - pip
          script:
            - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pytest -v homepage/test_homepage.py::test_bad_email