image: python:3.7

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - pip install virtualenv
            - virtualenv venv --python=python3.7
            - source venv/bin/activate
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - python -m pytest -v homepage/test_homepage.py::test_bad_email --junitxml=test-reports/report.xml

  custom:
    prod-pipeline:
      - step:
          name: Prod test
          script:
            - pip install virtualenv
            - virtualenv venv --python=python3.7
            - source venv/bin/activate
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - python -m pytest -v homepage/test_demoform.py::test_bad_email --url prod --junitxml=test-reports/report.xml

    staging1-pipeline:
        - step:
            name: Staging1 test
            script:
              - pip install virtualenv
              - virtualenv venv --python=python3.7
              - source venv/bin/activate
              - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - python -m pytest -v homepage/test_demoform.py::test_bad_email --url stag1 --junitxml=test-reports/report.xml

    staging2-pipeline:
      - step:
          name: Staging2 test
          script:
            - pip install virtualenv
            - virtualenv venv --python=python3.7
            - source venv/bin/activate
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - python -m pytest -v homepage/test_demoform.py::test_bad_email --url stag2 --junitxml=test-reports/report.xml